language: csharp

matrix:
  include:
    - dotnet: 2.1.105
      mono: none
      env: CONFIGURATION=Debug FRAMEWORK=netcoreapp2.0
    - dotnet: 2.1.105
      mono: none
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp2.0

before_script:
  - dotnet --info
  - dotnet restore

script:
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK tests/NSubstitute.Acceptance.Specs/NSubstitute.Acceptance.Specs.csproj
