os: Visual Studio 2022
build: off

environment:
  CONFIGURATION: Release

install:
  - set PATH=C:\Ruby25\bin;%PATH%
  - bundle install

before_test:
  - dotnet --info

test_script:
  - build\build.cmd --target All

artifacts:
- path: bin\Release\NSubstitute\*.nupkg
  name: NuGet

- path: bin\Release\NSubstitute\*.snupkg
  name: NuGet

- path: bin\Release\nsubstitute.github.com
  name: website
