os: Visual Studio 2017
build: off

environment:
  CONFIGURATION: Release

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install      

before_test:
  - dotnet --info

test_script:
  - build\build.cmd run build\build.fsx --target All

artifacts:
- path: bin\Release\NSubstitute\*.nupkg
  name: NuGet

- path: bin\Release\nsubstitute.github.com
  name: website
